from pydantic import BaseModel
from typing import Optional

class LessonCompletionRequest(BaseModel):
    # Auth credentials (hackathon style)
    email: str
    password_hash: str

    # Lesson Details
    language: str          # e.g., "Spanish"
    lesson_id: str         # e.g., "span_01"
    time_spent: int        # in minutes
    rating: int            # 1-5
    
    # Generated by LLM
    new_notes: str         # "User struggled with..."